# Generated by Django 2.1.7 on 2019-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
