# Generated by Django 2.1.7 on 2019-03-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_bin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='garbage_is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
