# Generated by Django 2.1.7 on 2019-03-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_bin_garbage_is_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.City'),
        ),
    ]
