# Generated by Django 2.1.7 on 2019-03-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_auto_20190330_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='worker',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste.Worker'),
        ),
        migrations.AlterField(
            model_name='people',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
